# Configuração do wallust
# Define onde aplicar os templates gerados

[settings]
# Paleta padrão de cores
palette = "dark16"

# Configurações de filtros
brightness = 1.0
contrast = 1.0
saturation = 1.0

# Onde aplicar os templates
[templates]
# Template para waybar
waybar = { template = "waybar.css", target = "~/.config/waybar/style.css" }

# Template para kitty
kitty = { template = "kitty.conf", target = "~/.config/kitty/wallust.conf" }

# Comandos para executar após gerar os templates
[settings.check]
waybar = "pkill waybar; WAYBAR_CONFIG=$HOME/.config/waybar/config.jsonc WAYBAR_STYLE=$HOME/.config/waybar/style.css waybar &"
kitty = "killall -SIGUSR1 kitty"
